[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  '@openzeppelin/=lib/openzeppelin-contracts/',
  'contracts/=src/'
]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
local = "http://localhost:8545"

[etherscan]
monad_testnet = { key = "${ETHERSCAN_API_KEY}" }
